using System;
using OpenCvSharp;
using NAudio.Wave;
using System.Text;
using System.Net.Http;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.IO;
using System.Diagnostics;
using Microsoft.VisualBasic.Devices;
using System.Windows.Media.Media3D;
using System.Net.Http.Json; // JsonContent.Create や PostAsJsonAsync に必要
using System.Net.Http.Headers; // AuthenticationHeaderValue に必要
using System.Windows.Threading;



namespace desktop
{

    public partial class MainWindow : System.Windows.Window
    {
        // UI control references (resolved at runtime via FindName to avoid depending on generated .g.cs)
        private System.Windows.Controls.Image imageDisplayRef;
        private System.Windows.Controls.ProgressBar volumeBarRef;
        private System.Windows.Controls.TextBlock faceScoreTextRef;
        private System.Windows.Controls.TextBlock audioScoreTextRef;
        private System.Windows.Controls.Button connectButtonRef;
        private System.Windows.Controls.Button audioConnectButtonRef;
        private System.Windows.Controls.ComboBox deviceComboRef;
        private System.Windows.Controls.ComboBox audioComboRef;

        // NOTE: InitializeComponent is generated by the XAML build step (.g.cs). Do not define it here to avoid duplicates.
        private CameraCapture _cameraCapture;
        private AudioCapture _audioCapture;
        private InAppDeviceService _deviceService;
        private FatigueUsecase _fatigueUsecase;
        private double _lastFaceScore = 0.0;
        private double _lastAudioScore = 0.0;
        private bool _connected = false;

        // ログイン情報を保持するプロパティ
        public string AccessToken { get; set; }
        public string CurrentUserId { get; set; }

        private readonly HttpClient _httpClient = new HttpClient();
        private DispatcherTimer _sendTimer; // 送信用のタイマー 

        private CameraDevice _camera;
        private AudioDevice _audio;

        public MainWindow()
        {
            // Ensure XAML is loaded even if designer-generated InitializeComponent isn't available.
            InitializeComponent();
            // Resolve named controls from XAML safely
            deviceComboRef = this.FindName("deviceCombo") as System.Windows.Controls.ComboBox;
            audioComboRef = this.FindName("audioCombo") as System.Windows.Controls.ComboBox;
            imageDisplayRef = this.FindName("imageDisplay") as System.Windows.Controls.Image;
            volumeBarRef = this.FindName("volumeBar") as System.Windows.Controls.ProgressBar;
            faceScoreTextRef = this.FindName("faceScoreText") as System.Windows.Controls.TextBlock;
            audioScoreTextRef = this.FindName("audioScoreText") as System.Windows.Controls.TextBlock;
            connectButtonRef = this.FindName("connectButton") as System.Windows.Controls.Button;
            audioConnectButtonRef = this.FindName("audioConnectButton") as System.Windows.Controls.Button;
            _cameraCapture = null;
            _audioCapture = null;


            _camera = new CameraDevice(0);
            _audio = new AudioDevice();


            // resolve in-app device service from DI
            _deviceService = App.CurrentApp.ServiceProvider.GetService(typeof(IDeviceService)) as InAppDeviceService;
            _fatigueUsecase = App.CurrentApp.ServiceProvider.GetService(typeof(FatigueUsecase)) as FatigueUsecase;
            if (_deviceService != null)
            {
                _deviceService.OnVideoFrame += DeviceService_OnVideoFrame;
                _deviceService.OnAudioData += DeviceService_OnAudioData;
            }

            // --- 自動送信タイマーの設定 (1分間隔) ---
            _sendTimer = new DispatcherTimer { Interval = TimeSpan.FromMinutes(1) };
            _sendTimer.Tick += async (s, e) => {
                await AutoSendFatigueAsync(); // 1分ごとにこのメソッドを呼ぶ
            };
            _sendTimer.Start();

            CompositionTarget.Rendering += UpdateFrame;

            // populate devices (fire-and-forget)
            _ = LoadDevicesAsync();
        }

        private async System.Threading.Tasks.Task LoadDevicesAsync()
        {
            try
            {
                // Enumerate local devices in C# and populate UI. User selection will be sent to Python on connect.
                var cams = EnumerateLocalCameras(6);
                var auds = EnumerateLocalAudioDevices();
                Dispatcher.Invoke(() =>
                {
                    var devCombo = deviceComboRef ?? this.FindName("deviceCombo") as System.Windows.Controls.ComboBox;
                    var audCombo = audioComboRef ?? this.FindName("audioCombo") as System.Windows.Controls.ComboBox;
                    if (devCombo != null) devCombo.Items.Clear();
                    if (audCombo != null) audCombo.Items.Clear();
                    foreach (var c in cams)
                    {
                        devCombo?.Items.Add(new System.Windows.Controls.ComboBoxItem { Content = c.Name, Tag = c.Id });
                    }
                    foreach (var a in auds)
                    {
                        audCombo?.Items.Add(new System.Windows.Controls.ComboBoxItem { Content = a.Name, Tag = a.Id });
                    }
                    if (devCombo != null && devCombo.Items.Count > 0) devCombo.SelectedIndex = 0;
                    if (audCombo != null && audCombo.Items.Count > 0) audCombo.SelectedIndex = 0;
                });
            }
            catch { }
        }

        private System.Collections.Generic.List<(string Id, string Name)> EnumerateLocalCameras(int maxIndex)
        {
            var list = new System.Collections.Generic.List<(string Id, string Name)>();
            for (int i = 0; i < maxIndex; i++)
            {
                try
                {
                    using var cap = new VideoCapture(i);
                    if (!cap.IsOpened())
                    {
                        cap.Release();
                        continue;
                    }
                    using var mat = new Mat();
                    if (cap.Read(mat) && !mat.Empty())
                    {
                        list.Add((i.ToString(), $"Camera {i}"));
                    }
                    cap.Release();
                }
                catch { }
            }
            return list;
        }

        private System.Collections.Generic.List<(string Id, string Name)> EnumerateLocalAudioDevices()
        {
            var list = new System.Collections.Generic.List<(string Id, string Name)>();
            try
            {
                int count = WaveIn.DeviceCount;
                for (int i = 0; i < count; i++)
                {
                    try
                    {
                        var caps = WaveIn.GetCapabilities(i);
                        var name = string.IsNullOrEmpty(caps.ProductName) ? $"Microphone {i}" : caps.ProductName;
                        list.Add(($"audio_{i}", $"Microphone {i}: {name}"));
                    }
                    catch { }
                }
            }
            catch
            {
                // fallback: if enumeration fails (permissions/driver issue), provide a default entry
                list.Add(("audio_default", "Default Microphone"));
                return list;
            }

            // Always offer a default device option at the top to handle permission-denied or exclusive-access cases
            if (list.Count == 0 || list[0].Id != "audio_default")
            {
                list.Insert(0, ("audio_default", "Default Microphone"));
            }
            return list;
        }

        private void UpdateFrame(object sender, EventArgs e)
        {
            var source = _camera?.GetFrameSource();
            if (source != null && imageDisplayRef != null)
            {
                imageDisplayRef.Source = source;
            }

            if (_audio != null && volumeBarRef != null)
            {
                volumeBarRef.Value = _audio.CurrentVolume;
            }
        }

        private void DeviceService_OnVideoFrame(object sender, VideoFrameEventArgsEx e)
        {
            try
            {
                Dispatcher.Invoke(() =>
                {
                    if (e.Jpeg != null && e.Jpeg.Length > 0 && imageDisplayRef != null)
                    {
                        using var ms = new System.IO.MemoryStream(e.Jpeg);
                        var img = new BitmapImage();
                        img.BeginInit();
                        img.CacheOption = BitmapCacheOption.OnLoad;
                        img.StreamSource = ms;
                        img.EndInit();
                        img.Freeze();
                        imageDisplayRef.Source = img;
                    }
                    if (faceScoreTextRef != null) faceScoreTextRef.Text = $"Face Fatigue: {e.FaceScore:F2}";
                });
                // store last score
                _lastFaceScore = e.FaceScore;
            }
            catch { }
        }

        private void DeviceService_OnAudioData(object sender, AudioDataEventArgsEx e)
        {
            try
            {
                Dispatcher.Invoke(() =>
                {
                    if (audioScoreTextRef != null) audioScoreTextRef.Text = $"Voice fatigue: {e.Score:F2}";
                    if (volumeBarRef != null) volumeBarRef.Value = Math.Min(1.0, e.Score);
                });
                _lastAudioScore = e.Score;
            }
            catch { }
        }

        private async void SendFatigueButton_Click(object sender, RoutedEventArgs e)
        {
            // 1. 認証チェック
            if (string.IsNullOrEmpty(AccessToken) || string.IsNullOrEmpty(CurrentUserId))
            {
                MessageBox.Show("ログイン情報が正しく保持されていません。再度ログインしてください。");
                return;
            }

            try
            {
                // 2. スコアを uint (0-100) に変換
                // _lastFaceScore, _lastAudioScore は 0.0 ~ 1.0 の前提
                uint face = (uint)Math.Clamp(Math.Round(_lastFaceScore * 100), 0, 100);
                uint voice = (uint)Math.Clamp(Math.Round(_lastAudioScore * 100), 0, 100);

                // 3. あなたの record 定義に合わせてインスタンス作成
                // コンストラクタ引数: UserId, GameId, FaceScore, VoiceScore, RecordedAt
                var requestBody = new FatigueCreateReq(
                    CurrentUserId,   // string UserId
                    null,            // string? GameId
                    face,            // uint FaceScore
                    voice,           // uint VoiceScore
                    DateTime.UtcNow  // DateTime RecordedAt
                );

                // 4. HTTP POST リクエストの構成
                using var request = new HttpRequestMessage(HttpMethod.Post, "https://test.sheeplab.net/api/fatigue");

                // Bearerトークンのセット
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", AccessToken);

                // JSONコンテンツのセット (System.Text.Json が自動で recorded_at 等に変換)
                request.Content = JsonContent.Create(requestBody);

                // 5. 送信
                var response = await _httpClient.SendAsync(request);

                if (response.IsSuccessStatusCode)
                {
                    MessageBox.Show($"サーバーへの送信に成功しました！\n顔: {face} / 声: {voice}");
                }
                else
                {
                    // サーバーからエラーが返った場合 (400, 422 等)
                    var errorBody = await response.Content.ReadAsStringAsync();
                    MessageBox.Show($"送信エラー ({response.StatusCode}):\n{errorBody}");
                }
            }
            catch (Exception ex)
            {
                // 通信断絶などの例外
                MessageBox.Show($"通信に失敗しました: {ex.Message}");
            }
        }




        private async void ConnectButton_Click(object sender, RoutedEventArgs e)
        {
            if (!_connected)
            {
                var devCombo = deviceComboRef ?? this.FindName("deviceCombo") as System.Windows.Controls.ComboBox;
                var item = devCombo?.SelectedItem as System.Windows.Controls.ComboBoxItem;
                if (item == null) return;
                var deviceId = item.Tag as string;
                try
                {
                    if (_deviceService != null)
                        await _deviceService.StartCaptureAsync(deviceId, "video");
                    if (connectButtonRef != null) connectButtonRef.Content = "Disconnect";
                    _connected = true;
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Failed to connect: " + ex.Message);
                }
            }
            else
            {
                try
                {
                    var devCombo = deviceComboRef ?? this.FindName("deviceCombo") as System.Windows.Controls.ComboBox;
                    var item = devCombo?.SelectedItem as System.Windows.Controls.ComboBoxItem;
                    var deviceId = item?.Tag as string;
                    if (_deviceService != null && deviceId != null)
                        await _deviceService.StopCaptureAsync(deviceId);
                }
                catch { }
                if (connectButtonRef != null) connectButtonRef.Content = "Connect";
                _connected = false;
            }
        }

        private bool _audioConnected = false;
        private async void AudioConnectButton_Click(object sender, RoutedEventArgs e)
        {
            if (!_audioConnected)
            {
                var audCombo = audioComboRef ?? this.FindName("audioCombo") as System.Windows.Controls.ComboBox;
                var item = audCombo?.SelectedItem as System.Windows.Controls.ComboBoxItem;
                if (item == null) return;
                var deviceId = item.Tag as string;
                try
                {
                    if (_deviceService != null)
                        await _deviceService.StartCaptureAsync(deviceId, "audio");
                    if (audioConnectButtonRef != null) audioConnectButtonRef.Content = "Disconnect Audio";
                    _audioConnected = true;
                }
                catch (Exception ex)
                {
                    // Common cause: microphone permission denied or device in exclusive use
                    var msg = ex.Message ?? string.Empty;
                    if (ex is UnauthorizedAccessException || msg.IndexOf("access", StringComparison.OrdinalIgnoreCase) >= 0 || msg.IndexOf("permission", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        MessageBox.Show("Microphone access was denied. Please allow microphone access for this app (Windows: Settings → Privacy → Microphone), close other apps that may be using the microphone, or run the app with elevated privileges.", "Microphone Access Denied", MessageBoxButton.OK, MessageBoxImage.Warning);
                    }
                    else
                    {
                        MessageBox.Show("Failed to connect audio: " + ex.Message, "Audio Connect Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                }
            }
            else
            {
                try
                {
                    var audCombo = audioComboRef ?? this.FindName("audioCombo") as System.Windows.Controls.ComboBox;
                    var item = audCombo?.SelectedItem as System.Windows.Controls.ComboBoxItem;
                    var deviceId = item?.Tag as string;
                    if (_deviceService != null && deviceId != null)
                        await _deviceService.StopCaptureAsync(deviceId);
                }
                catch { }
                if (audioConnectButtonRef != null) audioConnectButtonRef.Content = "Connect Audio";
                _audioConnected = false;
            }
        }

        // 送信用の共通メソッド（ボタンクリックの中身をここに移動）
        private async Task AutoSendFatigueAsync()
        {
            // 認証情報やIDがない、またはまだ計測スコアが更新されていない場合はスキップ
            if (string.IsNullOrEmpty(AccessToken) || string.IsNullOrEmpty(CurrentUserId)) return;

            try
            {
                uint face = (uint)Math.Clamp(Math.Round(_lastFaceScore * 100), 0, 100);
                uint voice = (uint)Math.Clamp(Math.Round(_lastAudioScore * 100), 0, 100);

                var requestBody = new FatigueCreateReq(
                    UserId: CurrentUserId,
                    GameId: null, // game_id
                    FaceScore: face,
                    VoiceScore: voice,
                    RecordedAt: DateTime.UtcNow
                ); ;

                using var request = new HttpRequestMessage(HttpMethod.Post, "https://test.sheeplab.net/api/fatigue");
                request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", AccessToken);
                request.Content = JsonContent.Create(requestBody);

                var response = await _httpClient.SendAsync(request);

                if (response.IsSuccessStatusCode)
                {
                    // ログに記録（MessageBoxだと作業の邪魔になるため）
                    Debug.WriteLine($"[AutoSend Success] {DateTime.Now}: Face={face}, Voice={voice}");
                }
                else
                {
                    Debug.WriteLine($"[AutoSend Failed] {response.StatusCode}");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"[AutoSend Error] {ex.Message}");
            }
        }

        protected override void OnClosed(EventArgs e)
        {
            CompositionTarget.Rendering -= UpdateFrame;
            _camera?.Dispose();
            _audio?.Dispose();
            base.OnClosed(e);
        }
    }

}
